services:
  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/stocks
    depends_on:
      - db
  db:
    image: postgres:18
    container_name: stock-trend-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stocks
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
